ARG FEDORA_VERSION="latest"

FROM docker.io/krystalcode/f_fedora:${FEDORA_VERSION}

# "latest" would install the development version.
ARG K9S_VERSION="v0.50.2"

RUN dnf -y install golang && \
    dnf -y clean all && \
    go install github.com/derailed/k9s@${K9S_VERSION}

COPY k9s.sh /root/.bashrc.d/
