ARG FEDORA_VERSION="latest"
ARG NVM_VERSION="latest"

FROM docker.io/krystalcode/f_atuin:${FEDORA_VERSION}-latest AS atuin

FROM docker.io/krystalcode/f_just:${FEDORA_VERSION}-latest AS just

FROM docker.io/krystalcode/f_nvm:${FEDORA_VERSION}-${NVM_VERSION}

# Set the Node.js version to the latest available.
ARG NODE_VERSION="26"

# `libatomic` is required by Node JS.
# `yt-dlp-ejs` - see https://github.com/yt-dlp/ejs/issues/72.
RUN dnf -y install yt-dlp libatomic pip && \
    dnf -y clean all && \
    pip install -U yt-dlp-ejs

    # Install the right Node.js version and set it as default.
RUN . ${HOME}/.nvm/nvm.sh && \
    nvm install ${NODE_VERSION} && \
    printf '\n%s\n%s%s\n\n' '# Use default node version.' "nvm use " ${NODE_VERSION}  >> ~/.bashrc && \

    # Globally install Deno, recommended JavaScript engine for `yt-dlp`.
    nvm use ${NODE_VERSION} && \
    npm install -g deno

COPY download.sh /usr/local/bin/download

# Add "atuin".
COPY --from=atuin /usr/bin/atuin /usr/bin/
COPY --from=atuin /root/.bashrc.d/atuin-client.sh /root/.bashrc.d/

# Add "just".
COPY --from=just /usr/bin/just /usr/bin/
COPY --from=just /root/.bashrc.d/just.aliases.sh /root/.bashrc.d/
