ARG FEDORA_VERSION="latest"
ARG NVM_VERSION="latest"

FROM docker.io/krystalcode/f_nvm:${FEDORA_VERSION}-${NVM_VERSION} as node

# Set the Node.js version to the latest available.
ARG NODE_VERSION="26"

RUN dnf install -y jq && dnf clean all

ENV SCREENSY_REPO="screensy/screensy"
ENV SCREENSY_VERSION="latest"
ENV SCREENSY_TMP_DIR="/app"
RUN <<COMMAND
set -eux
if [ "${SCREENSY_VERSION}" = "latest" ];
then
    SCREENSY_VERSION=$(curl --silent "https://api.github.com/repos/${SCREENSY_REPO}/tags" | jq -r '.[0].name' | sed -E 's/.*"([^"]+)".*/\1/')
fi

mkdir -p ${SCREENSY_TMP_DIR}
cd ${SCREENSY_TMP_DIR}
git clone --recursive --depth=1 --branch=${SCREENSY_VERSION} https://github.com/${SCREENSY_REPO}.git .
COMMAND

    # Install the right Node.js version and set it as default.
RUN . ${HOME}/.nvm/nvm.sh && \
    nvm install ${NODE_VERSION} && \
    printf '\n%s\n%s%s\n\n' '# Use default node version.' "nvm use " ${NODE_VERSION}  >> ~/.bashrc && \
    nvm use ${NODE_VERSION} && \
    cd ${SCREENSY_TMP_DIR}/screensy-website && \
    npm install typescript@4.4.2 -g && \
    npx tsc

FROM docker.io/krystalcode/f_fedora:${FEDORA_VERSION} as go

RUN dnf install -y golang git && dnf clean all

ENV SCREENSY_BUILD_DIR="/app/screensy-website"

WORKDIR ${SCREENSY_BUILD_DIR}

COPY --from=node ${SCREENSY_BUILD_DIR}/main.go ./
COPY --from=node ${SCREENSY_BUILD_DIR}/go.mod ./

RUN go mod download && \
    # This command fixes the following error, probably an issue with the
    # screensy code that should be fixed there.
    # Error: main.go:13:2: missing go.sum entry for module providing package
    # golang.org/x/text/language (imported by screensy); to add: go get screensy
    go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -o screensy-website . && \
    pwd && ls -ahl

FROM docker.io/krystalcode/f_nvm:${FEDORA_VERSION}-${NVM_VERSION}

# Set the Node.js version to the latest available.
ARG NODE_VERSION="26"

ENV SCREENSY_APP_DIR="/app"
ENV SCREENSY_BUILD_DIR="/app/screensy-website"

WORKDIR ${SCREENSY_APP_DIR}

COPY --from=node ${SCREENSY_BUILD_DIR}/screensy.js ./
COPY --from=node ${SCREENSY_BUILD_DIR}/screensy.js.map ./
COPY --from=node ${SCREENSY_BUILD_DIR}/screensy.ts ./
COPY --from=node ${SCREENSY_BUILD_DIR}/styles.css ./
COPY --from=node ${SCREENSY_BUILD_DIR}/translations/ ./translations

COPY --from=go ${SCREENSY_BUILD_DIR}/screensy-website ./

EXPOSE 8080

CMD ["./screensy-website"]
