ARG FEDORA_VERSION="latest"

FROM docker.io/krystalcode/f_fedora:${FEDORA_VERSION} AS cargo

RUN dnf -y install cargo && \
    dnf -y clean all && \
    cargo install just

FROM docker.io/krystalcode/f_fedora:${FEDORA_VERSION}

COPY --from=cargo /root/.cargo/bin/just /usr/bin/
