ARG DEBIAN_VERSION="12"

FROM docker.io/library/debian:${DEBIAN_VERSION} AS cargo

RUN apt-get update && \
    apt-get -y install curl && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    /root/.cargo/bin/cargo install just


FROM docker.io/library/debian:${DEBIAN_VERSION}

COPY --from=cargo /root/.cargo/bin/just /usr/bin/
