ARG DEBIAN_VERSION="latest"

FROM docker.io/krystalcode/d_debian:${DEBIAN_VERSION} AS cargo

RUN apt-get update && \
    apt-get -y install curl && \
    apt -y install build-essential && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    /root/.cargo/bin/cargo install just

FROM docker.io/krystalcode/d_debian:${DEBIAN_VERSION}

COPY --from=cargo /root/.cargo/bin/just /usr/bin/

# Add .bashrc extensions.
COPY .bashrc.d/just.aliases.sh /root/.bashrc.d/
