ARG DEBIAN_VERSION="latest"

FROM docker.io/library/debian:${DEBIAN_VERSION}

ARG OH_MY_POSH_VERSION="latest"

# Allow extending .bashrc with files.
# Unless we copy the file first, it is not found.
COPY .bashrc.extend.sh /tmp/.bashrc.extend.sh
RUN cat /tmp/.bashrc.extend.sh >> ~/.bashrc && \
    rm /tmp/.bashrc.extend.sh && \
    mkdir ~/.bashrc.d

# Add .bashrc extensions.
COPY .bashrc.d/aliases.sh /root/.bashrc.d/aliases.sh
COPY .bashrc.d/variables.sh /root/.bashrc.d/variables.sh

# Dotenv.
ENV DOTENV_REPO="bashup/dotenv"
RUN apt-get update && \
    apt-get -y install curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    curl -L -o /usr/bin/dotenv https://raw.githubusercontent.com/${DOTENV_REPO}/refs/heads/master/dotenv && \
    chmod +x /usr/bin/dotenv

# `oh-my-posh`.
ENV OH_MY_POSH_REPO="JanDeDobbeleer/oh-my-posh"
RUN <<COMMAND
set -eux
if [ "${OH_MY_POSH_VERSION}" = "latest" ];
then
    OH_MY_POSH_VERSION=$(curl --silent "https://api.github.com/repos/${OH_MY_POSH_REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
fi
    curl -L -o /usr/bin/oh-my-posh https://github.com/${OH_MY_POSH_REPO}/releases/download/${OH_MY_POSH_VERSION}/posh-linux-amd64 && \
    chmod +x /usr/bin/oh-my-posh
COMMAND

COPY oh-my-posh.runnah.minimal.omp.json /root/.config/oh-my-posh/themes/runnah.minimal.omp.json
COPY .bashrc.d/oh-my-posh.sh /root/.bashrc.d/
